# Generated by Django 5.0.3 on 2024-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=20)),
                ('customer_last_name', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=20)),
                ('customer_mobile_no', models.IntegerField()),
                ('food_mode', models.CharField(choices=[('TEA', 'Tea'), ('COFFEE', 'Coffee'), ('POHE', 'Pohe'), ('UPMA', 'Upma'), ('DOSA', 'Dosa')], max_length=20)),
            ],
        ),
    ]
